# Generated by Django 3.0.11 on 2021-02-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Day',
            new_name='day',
        ),
        migrations.DeleteModel(
            name='Workers',
        ),
    ]
