# Generated by Django 3.0.11 on 2021-02-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210208_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refences',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
